"""merge invested_amount check constraints

Revision ID: 28d553832bec
Revises: b4e34b00b599
Create Date: 2026-07-09 20:50:55.793318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d553832bec'
down_revision = 'b4e34b00b599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
