"""add invested_amount not exceed full_amount constraint

Revision ID: b4e34b00b599
Revises: 3061cdc0debd
Create Date: 2026-07-07 21:24:14.957288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e34b00b599'
down_revision = '3061cdc0debd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
